### ISSUE TITLE
admission.k8s.io/v1 AdmissionReview response requires uid

### ISSUE THREAD

**Issue by mingfang** [open-policy-agent/library#34]
According to https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/ the response needs to look like this
```yaml
{
  "apiVersion": "admission.k8s.io/v1",
  "kind": "AdmissionReview",
  "response": {
    "uid": "<value from request.uid>",
    "allowed": true
  }
}
```
